set encoding=UTF-8
set relativenumber
set completeopt=menuone,noselect
set mouse=a
" set splitleft
set splitbelow
set expandtab
set tabstop=2
set shiftwidth=2
set number
set ignorecase
set smartcase
set incsearch
set diffopt+=vertical
set hidden
set nobackup
set nowritebackup
set cmdheight=1
set shortmess+=c
set signcolumn=yes
set updatetime=750
set colorcolumn=110
set scrolloff=5
set wildmenu
set numberwidth=1
set showcmd
set nowrap
set showmatch
set ruler 
set noshowmode
set nohlsearch
